version: "3.8"

services:

  #################################
  # Book: The Book microservice
  #################################
  order:
    build:
      context: ./
      dockerfile: Dockerfile
    image: project/order:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/gym_delivery
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"
